_google_tag_container:
  type: mapping
  label: 'Container settings'
  mapping:
    container_id:
      type: string
      label: 'Container ID'
      #translatable: true
    data_layer:
      type: string
      label: 'Data layer'
      #translatable: true
    include_classes:
      type: boolean
      label: 'Add classes to the data layer'
    whitelist_classes:
      type: string
      label: 'White-listed classes'
      #translatable: true
    blacklist_classes:
      type: string
      label: 'Black-listed classes'
      #translatable: true
    include_environment:
      type: boolean
      label: 'Include an environment'
    environment_id:
      type: string
      label: 'Environment ID'
      #translatable: true
    environment_token:
      type: string
      label: 'Environment token'
      #translatable: true
    path_toggle:
      type: string
      label: 'Add snippet on specific paths'
      #translatable: true
    path_list:
      type: string
      label: 'Listed paths'
      #translatable: true
    role_toggle:
      type: string
      label: 'Add snippet for specific roles'
      #translatable: true
    role_list:
      type: sequence
      label: 'Selected roles'
      sequence:
        type: string
        label: 'Role'
      #translatable: true
    status_toggle:
      type: string
      label: 'Add snippet for specific statuses'
      #translatable: true
    status_list:
      type: string
      label: 'Listed statuses'
      #translatable: true
